# This is a basic workflow to help you get started with Actions

name: lab 2 Workflow

on: [push] 
  jobs:
    build:
    
      run-on: ubuntu-latest
      
      steps:
      -uses: actions/checkout@v2
      -name: Run a one-line script
        run: echo "Our secret is ${{secrets.LAB_SECRET}}
 
